#!/usr/bin/env python3
"""
Remove ephemeral workspace CSVs after validation (POLISH-03).

Deletes ``to_queue_pending_validate.csv`` and optionally ``to_queue_pending.csv``
from the pipeline workspace (not archived — they are regenerated by slskd runs).

Usage::

    python3 pipeline_cleanup.py
    python3 pipeline_cleanup.py --workspace data
    python3 pipeline_cleanup.py --ephemeral
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from slskd_workspace import (
    PENDING_RETRY_FILENAME,
    PENDING_VALIDATE_FILENAME,
    ensure_workspace_layout,
    remove_ephemeral_pending_csvs,
    resolve_workspace,
)


def _die(msg: str, code: int = 1) -> None:
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Remove ephemeral pending CSVs from the pipeline workspace."
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=None,
        help="Pipeline data directory (default: ./data/, or cwd if legacy flat layout)",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help=f"Remove only {PENDING_VALIDATE_FILENAME}",
    )
    parser.add_argument(
        "--ephemeral",
        action="store_true",
        help=f"Remove {PENDING_VALIDATE_FILENAME} and {PENDING_RETRY_FILENAME}",
    )
    args = parser.parse_args()

    if args.validate_only and args.ephemeral:
        _die("Use either --validate-only or --ephemeral, not both.")

    workspace = resolve_workspace(args.workspace)
    ensure_workspace_layout(workspace)

    removed = remove_ephemeral_pending_csvs(
        workspace, include_retry_pending=args.ephemeral
    )
    if not removed:
        print("No ephemeral pending CSVs to remove.", file=sys.stderr)
        return
    for path in removed:
        print(f"Removed {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
